version: '3.7'

services:
  pocdeviceintegration:
    restart: unless-stopped
    container_name: pocdeviceintegration
    image: springboot-docker-compose-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - '/etc/timezone:/etc/timezone:ro'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://192.168.0.40:5432/poc_devices
    ports:
      - '8082:80'
    networks:
      - pocdevicenet

networks:
  pocdevicenet:
    driver: bridge
